# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u53c2\u4e0e\u8005',
                'verbose_name_plural': '\u9879\u76ee\u53c2\u4e0e\u8005',
            },
        ),
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_st_date', models.DateField(verbose_name='\u9879\u76ee\u5b9e\u9645\u5f00\u59cb\u65f6\u95f4')),
                ('act_ed_date', models.DateField(verbose_name='\u9879\u76ee\u5b9e\u9645\u7ed3\u675f\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u5b9e\u9645\u65f6\u95f4',
                'verbose_name_plural': '\u9879\u76ee\u5b9e\u9645\u65f6\u95f4',
            },
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='%s/%s/', verbose_name='\u8bbe\u8ba1\u56fe')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='\u786e\u8ba4\u4fe1\u606f')),
                ('pic_date_publish', models.DateField(auto_now_add=True, verbose_name='\u8bbe\u8ba1\u56fe\u53d1\u5e03\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bbe\u8ba1\u56fe',
                'verbose_name_plural': '\u8bbe\u8ba1\u56fe',
            },
        ),
        migrations.CreateModel(
            name='PlanFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_st_date', models.DateField(verbose_name='\u9879\u76ee\u9884\u8ba1\u5f00\u59cb\u65f6\u95f4')),
                ('pre_ed_date', models.DateField(verbose_name='\u9879\u76ee\u9884\u8ba1\u7ed3\u675f\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u8ba1\u5212\u65f6\u95f4',
                'verbose_name_plural': '\u9879\u76ee\u8ba1\u5212\u65f6\u95f4',
            },
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50, verbose_name='\u9879\u76ee\u7f16\u53f7')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Organization', verbose_name='\u516c\u53f8')),
            ],
            options={
                'verbose_name': '\u9879\u76ee',
                'verbose_name_plural': '\u9879\u76ee',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u5de5\u5e8f\u540d\u79f0')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Organization', verbose_name='\u516c\u53f8')),
            ],
            options={
                'verbose_name': '\u5de5\u5e8f',
                'verbose_name_plural': '\u5de5\u5e8f',
            },
        ),
        migrations.CreateModel(
            name='ProFlowBlank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_flow_name', models.CharField(max_length=50, verbose_name='\u9879\u76ee\u6d41\u7a0b\u5757')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Pro', verbose_name='\u9879\u76ee')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u6d41\u7a0b\u5757',
                'verbose_name_plural': '\u9879\u76ee\u6d41\u7a0b\u5757',
            },
        ),
        migrations.CreateModel(
            name='Subitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_st_date', models.DateField(auto_now_add=True, verbose_name='\u5b50\u9879\u76ee\u5f00\u59cb\u65f6\u95f4')),
                ('pro_flow_blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProFlowBlank', verbose_name='\u9879\u76ee\u6d41\u7a0b\u5757')),
                ('processes', models.ManyToManyField(to='project.Process', verbose_name='\u5de5\u5e8f')),
            ],
            options={
                'verbose_name': '\u5b50\u9879\u76ee',
                'verbose_name_plural': '\u5b50\u9879\u76ee',
            },
        ),
        migrations.AddField(
            model_name='planflow',
            name='pro_flow_blank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProFlowBlank', verbose_name='\u9879\u76ee\u6d41\u7a0b\u5757'),
        ),
        migrations.AddField(
            model_name='pic',
            name='pro_flow_blank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProFlowBlank', verbose_name='\u9879\u76ee\u6d41\u7a0b\u5757'),
        ),
        migrations.AddField(
            model_name='actual',
            name='pro_flow_blank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProFlowBlank', verbose_name='\u9879\u76ee\u6d41\u7a0b\u5757'),
        ),
        migrations.AddField(
            model_name='actor',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Pro', verbose_name='\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='actor',
            name='pro_actors',
            field=models.ManyToManyField(to='company.Staff', verbose_name='\u9879\u76ee\u53c2\u4e0e\u8005'),
        ),
    ]
