# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_content', models.CharField(max_length=50, verbose_name='\u884c\u4e3a')),
                ('action_type', models.CharField(choices=[('0', '\u4e00\u822c\u884c\u4e3a'), ('1', '\u8bbe\u8ba1\u56fe'), ('3', '\u62a5\u4ef7'), ('4', '\u5408\u540c')], max_length=20, verbose_name='\u884c\u4e3a\u7c7b\u578b')),
                ('pro_flow_blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProFlowBlank', verbose_name='\u9879\u76ee\u6d41\u7a0b\u5757')),
            ],
            options={
                'verbose_name': '\u884c\u4e3a',
                'verbose_name_plural': '\u884c\u4e3a',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='pic',
            name='pro_flow_blank',
        ),
        migrations.RemoveField(
            model_name='process',
            name='org',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='pro_flow_blank',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='processes',
        ),
        migrations.DeleteModel(
            name='Pic',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='Subitem',
        ),
    ]
