# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_sex',
            new_name='sex',
        ),
    ]
