# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-01 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_join',
            field=models.DateField(auto_now_add=True, verbose_name='\u5165\u804c\u65f6\u95f4'),
        ),
    ]
