# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-03 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_organization_company_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='department',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
